function [fitresult, gof] = gausFitCustom(thMics, roMics, micAmpDataShifted)
%CREATEFIT(THMICS,ROMICS,MICAMPDATASHIFTED)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : thMics
%      Y Input : roMics
%      Z Output: micAmpDataShifted
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Nov-2022 00:24:19


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( thMics, roMics, micAmpDataShifted );

% Set up fittype and options.
ft = fittype( 'b*exp(-((x0 - x)^2)*0.5*sx + -((y0 - y)^2)*0.5*sy)', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.417921324392185 0.958893447208648 0.85540143918067 0.399658821860232 0.510288092757317];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, [xData, yData], zData );
% legend( h, 'untitled fit 1', 'micAmpDataShifted vs. thMics, roMics', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'thMics', 'Interpreter', 'none' );
% ylabel( 'roMics', 'Interpreter', 'none' );
% zlabel( 'micAmpDataShifted', 'Interpreter', 'none' );
% grid on
% view( 188.5, 59.3 );


